### PR TITLE
Fix ghc 8.2.1

### PR DESCRIPTION
**Pull request by ch1bo**

### CODE REVIEW

**Comment by dmalikov** [comment]
@ch1bo does it work for you? `hdevtools check` just stuck for me and doesn't seem to be checking anything.

**Comment by ZedPea** [comment]
Any more on this? It also hangs for me, and doesn't appear to be using any cpu or memory

**Comment by ch1bo** [comment]
I am still away from a laptop another couple of days, but IIRC these fixes worked for me..make sure no old hdevtools instance is running before trying this branch.

With other things fixed on master, eventual errors should be reported and no silent failures!?

**Comment by ZedPea** [comment]
Ah, it seems to be something to do with stack. When I try it on a test file in my home directory for example, it works fine, using the global ghc-8.2.1, but when I'm in my project directory it just hangs. 

I'm currently using the stack nightly resolver, but if I change it to lts-9.6 it works fine. The obvious difference is the nightly uses ghc-8.2.1, but like I said that works fine when not in a stack project. Not sure what's going on.

**Comment by ch1bo** [comment]
Okay..the ghc-8.2.1 fix is not yet merged and released and thus the nightly snapshot project does build and installs the fixed version if you do `stack install hdevtools` from there. to try this fix with the nightly 8.2.1 project you need to make sure the patched version is built from source against 8.2.1 and available on PATH

⁣Sent from TypeApp ​

**Comment by ZedPea** [comment]
So I have to install the fork by editing the cloned stack.yaml and setting it to nightly?

If so I did
`git clone https://github.com/hdevtools/hdevtools`
`git checkout fix-ghc-8.2.1`
`sed -i 's/lts-9.0/nightly-2017-09-29/' stack.yaml`
`stack install`

and I got this error:
```
Linking .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.0.2/build/hdevtools/hdevtools ...
/usr/bin/ld.gold: error: cannot find -ltinfo
/home/zach/.stack/programs/x86_64-linux/ghc-nopie-8.2.1/lib/ghc-8.2.1/ghc-8.2.1/libHSghc-8.2.1.a(Terminal.o)(.text+0x142): error: undefined reference to 'set_curterm'
/home/zach/.stack/programs/x86_64-linux/ghc-nopie-8.2.1/lib/ghc-8.2.1/ghc-8.2.1/libHSghc-8.2.1.a(Terminal.o)(.text+0x1c0): error: undefined reference to 'set_curterm'
/home/zach/.stack/programs/x86_64-linux/ghc-nopie-8.2.1/lib/ghc-8.2.1/ghc-8.2.1/libHSghc-8.2.1.a(Terminal.o)(.text+0x263): error: undefined reference to 'set_curterm'
/home/zach/.stack/programs/x86_64-linux/ghc-nopie-8.2.1/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o)(.text.r9DX_info+0x102): error: undefined reference to 'tigetnum'
/home/zach/.stack/programs/x86_64-linux/ghc-nopie-8.2.1/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o)(.text.s9PJ_info+0xf8): error: undefined reference to 'set_curterm'
/home/zach/.stack/programs/x86_64-linux/ghc-nopie-8.2.1/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o)(.text.s9PJ_info+0x14a): error: undefined reference to 'del_curterm'
/home/zach/.stack/programs/x86_64-linux/ghc-nopie-8.2.1/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o)(.text.s9PJ_info+0x271): error: undefined reference to 'setupterm'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package hdevtools-0.1.6.0 using:
      /home/zach/.stack/setup-exe-cache/x86_64-linux-nopie/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1 --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-2.0.0.2 build exe:hdevtools --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```


If I install libtinfo I get this output
```
Network-2.6.3.2: configure
Progress: 1/2
--  While building package network-2.6.3.2 using:
      /tmp/stack31339/network-2.6.3.2/.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-2.0.0.2/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-2.0.0.2 configure --with-ghc=/home/zach/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.2.1/bin/ghc --with-ghc-pkg=/home/zach/.stack/programs/x86_64-linux/ghc-tinfo6-nopie-8.2.1/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/pkgdb --libdir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/lib --bindir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/bin --datadir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/share --libexecdir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/libexec --sysconfdir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/etc --docdir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/doc/network-2.6.3.2 --htmldir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/doc/network-2.6.3.2 --haddockdir=/home/zach/.stack/snapshots/x86_64-linux-tinfo6-nopie/nightly-2017-09-29/8.2.1/doc/network-2.6.3.2 --dependency=base=base-4.10.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=unix=unix-2.7.2.2
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/zach/hdevtools/.stack-work/logs/network-2.6.3.2.log

    [1 of 2] Compiling Main             ( /tmp/stack31339/network-2.6.3.2/Setup.hs, /tmp/stack31339/network-2.6.3.2/.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-2.0.0.2/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /home/zach/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack31339/network-2.6.3.2/.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-2.0.0.2/setup/StackSetupShim.o )
    Linking /tmp/stack31339/network-2.6.3.2/.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-2.0.0.2/setup/setup ...
    Configuring network-2.6.3.2...
    configure: WARNING: unrecognized options: --with-compiler
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for gcc... /usr/bin/gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... configure: error: in `/tmp/stack31339/network-2.6.3.2':
    configure: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details
```
I think I'm probably doing something wrong, and I imagine you don't want to dig through logs if you don't have a laptop. I'll just wait until it's merged and try again I guess.

**Comment by unit73e** [comment]
Just to inform that I made an hdevtools package for Arch Linux based on this branch and so far it seems to be working fine.

**Comment by ch1bo** [comment]
So lets merge this on master now and try to get that released soon!

**Pull request merged**
