### PR TITLE
Add nostack option, implement per-project config files

### PR DESCRIPTION
**Pull request by pacak**
https://github.com/hdevtools/hdevtools/issues/58 - this

### CODE REVIEW

**Comment by ch1bo** [comment]
Looks ok, can you update the `CHANGELOG.md` and `README.md` with your changes and how to use the `.hdevtoolsrc` override?

**Comment by pacak** [comment]
Will do.

I think there was a slight problem with parameter handling - I having problems understanding logic of `cmdargs` breaks argument into groups: --noStack should probably be global rather than specified for every individual subcommand.

**Comment by pacak** [comment]
Updated docs, fixed name that went missing for `--no-th` option, minor cosmetic bikeshedding, `-S` option is now short for `--nostack`, bumped version.

**Comment by pacak** [comment]
Also fixed failure in ancient ghc I introduced. Not sure about remaining bugs.

**Comment by pacak** [comment]
Right now MR is a bit broken by https://github.com/jamesdbrock/hdevtools/commit/8a270f6f3021326e17278036f9e36c457b23f116

**Comment by pacak** [comment]
Fixed problem mentioned in previous comment, works for me now.

**Comment by ch1bo** [comment]
Seems like travis is broken for `cabal-install` builds, but I'll merge this now

**Pull request merged**
